<!--Información del curso-->
<img align="left" style="padding-right:10px;" src="figuras/banner_cd.png">

<center><h1 style="font-size:2em;color:#2467C0"> Numpy - Parte 2 </h1></center>

<center><h4 style="font-size:2em;color:#840700"> Estadística Descriptiva </h4></center>

<br>
<table>
<col width="550">
<col width="450">
<tr>
<td><img src="figuras/arreglos_numpy.png" align="middle" style="width:500px"/></td>
<td align="left-align">

Numpy es un paquete que provee a Python con arreglos multidimensionales de alta eficiencia y diseñados para cálculo científico, los cuales son variables tipo array, como los que se muestran a continuación:

Un arreglo o array puede contener:

* tiempos discretos de un experimento o simulación.
    
* señales grabadas por un instrumento de medida.
   
* pixeles de una imagen, etc.

**Importante** Numpy solo permite un tipo de objeto para los elementos del arreglo 

Para mayor información  http://www.numpy.org/ 
    
<br>
</td>
</tr>
</table>

# Librerias

In [1]:
import numpy as np
import matplotlib.pyplot as plt

##  Funciones de  Estadística Descriptiva

A menudo, cuando se tienen una gran cantidad de datos, un primer paso es calcular parámetros estadísticos para entender los datos en cuestión. Quizás los parámetros más comunes son la media y la desviación estándar, que permiten resumir los valores "típicos" en un conjunto de datos, pero también son útiles otros (suma, producto, mediana, mínimo y máximo, cuantiles, etc. )

#### Ejemplo de la función *sum()*


La función *sum()* puede actuar de diferentes formas, como se puede ver en la siguiente imagen

<img align="left" width="300"  float= "none" align="middle" src="figuras/arreglo5.png">

In [2]:
# Definimos el arreglo "a"
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
# Aplicando la función suma sin restricción
np.sum(a)

np.int64(21)

In [4]:
# Aplicando la función suma a lo largo del eje = 0 (axis=0 o -2)
np.sum(a, axis=0)

array([5, 7, 9])

In [5]:
# Aplicando la función suma a lo largo del eje = 1 (axis=1 o -1 )
np.sum(a, axis = 1)

array([ 6, 15])

Existen varias funciones de Estadística Descriptiva proporcionadas por Numpy. Además, la mayoría de ellas tienen una contraparte segura para *NaN* (not a number) que calcula el resultado mientras ignora los valores faltantes, que están marcados por el valor especial de *NaN*. Algunas de estas funciones seguras para NaN no se agregaron hasta NumPy 1.8.

La siguiente tabla proporciona una lista de funciones disponibles en Numpy:

| Nombre de la función | Versión segura para NaN | Descripción |
| ------------------- | --------------------- | ----------------------------------------------- |
| ``np.sum`` | ``np.nansum`` | Calcular suma de elementos |
| ``np.prod`` | ``np.nanprod`` | Calcular producto de elementos |
| ``np.mean`` | ``np.nanmean`` | Calcular media de elementos |
| ``np.std`` | ``np.nanstd`` | Calcular desviación estándar |
| ``np.var`` | ``np.nanvar`` | Calcular varianza |
| ``np.min`` | ``np.nanmin`` | Encuentra el valor mínimo |
| ``np.max`` | ``np.nanmax`` | Encuentra el valor máximo |
| ``np.argmin`` | ``np.nanargmin`` | Encontrar índice de valor mínimo |
| ``np.argmax`` | ``np.nanargmax`` | Encontrar índice de valor máximo |
| ``np.median`` | ``np.nanmedian`` | Calcular la mediana de los elementos |
| ``np.percentile`` | ``np.nanpercentile`` | Calcular estadísticas basadas en rangos de elementos |
| ``np.any`` | N / A    | Evaluar si algún elemento es verdadero |
| ``np.all`` | N / A    |Evaluar si todos los elementos son verdaderos |

#### Ejercicio de ejemplo


Utilice el siguiente arreglo para encontrar lo que se pide en cada pregunta

arreglo = np.arange(-15, 15).reshape(5, 6) ** 2

<img align="left" width="300"  float= "none" align="middle" src="figuras/arreglo6.png">

In [6]:
arreglo = np.arange(-15, 15).reshape(5, 6) ** 2
print(arreglo)

[[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]


<font color='Green'> 1. El valor máximo de cada columna (uno por columna)  </font > 

In [7]:
print(np.max(arreglo, axis=0))

[225 196 169 144 169 196]


<font color='Green'> 2. El valor promedio de cada columna (uno por columna)  </font > 

In [8]:
print(np.mean(arreglo, axis=0))

[81. 76. 73. 72. 73. 76.]


<font color='Green'> 3. La posición del elemento más pequeño  </font > 

In [9]:
#Para el caso del arreglo el elemento más pequeño es 0
#Nos devuelve la posición general en el arreglo
print(np.min(arreglo, axis=1).argmin())
print(np.min(arreglo, axis=0).argmin())


2
3


In [10]:
#Nos devuelve los índices de la posición en coordenadas (fila, columna)
#Primero encontramos el elemento más pequeño en cada fila
#Seguimos con encontrar el elemento más pequeño en cada columna



# Ejercicios

### 1. considere ahora el siguiente arreglo:


In [11]:
arreglo = np.arange(-16, 16,2).reshape(4,4 ) **2
print(arreglo)

[[256 196 144 100]
 [ 64  36  16   4]
 [  0   4  16  36]
 [ 64 100 144 196]]


<div class="alert alert-success">
       
a) El valor máximo de cada fila (uno por fila)

</div> 

<div class="alert alert-success">
       
 b) El valor promedio de cada columna (uno por columna) 
</div> 

<div class="alert alert-success">      
c) La posición del elemento más pequeño 
</div> 

<div class="alert alert-success">
       
 d) La suma de cada columna
</div> 

<div class="alert alert-success">
       
 e) El valor de la mediana de cada fila 
</div> 

<div class="alert alert-success">   
    
f) ¿Cuantos elementos en total tiene el arreglo, asi como número de filas y columnas ?. 
    
</div> 