<!--Información del curso-->
<img align="left" style="padding-right:10px;" src="figuras/banner_cd.png">

<center><h1 style="font-size:2em;color:#2467C0"> Numpy - Parte 1 </h1></center>

<center><h4 style="font-size:2em;color:#840700"> Arreglos de Numpy </h4></center>

<br>
<table>
<col width="550">
<col width="450">
<tr>
<td><img src="figuras/arreglos_numpy.png" align="middle" style="width:500px"/></td>
<td align="left-align">

Numpy es un paquete que provee a Python con arreglos multidimensionales de alta eficiencia y diseñados para cálculo científico, los cuales son variables tipo array, como los que se muestran a continuación:

Un arreglo o array puede contener:

* tiempos discretos de un experimento o simulación.
    
* señales grabadas por un instrumento de medida.
   
* pixeles de una imagen, etc.

**Importante** Numpy solo permite un tipo de objeto para los elementos del arreglo 

Para mayor información  http://www.numpy.org/ 
    
<br>
</td>
</tr>
</table>

In [1]:
#Versión instalada numpy
import numpy
numpy.__version__

'2.3.2'

A manera de convención se utiliza **_np_** como el alias de numpy 

In [2]:
import numpy as np

# ¿Por qué aprender a utilizar la librería NumPy?

La respuesta vendría dada por el rendimiento del lenguaje de programación Python a la hora de llevar a cabo cálculos numéricos.


<img align="left" width="600"  float= "none" align="middle" src="figuras/NumpyPython1.png">


## Ilustremos este hecho con un sencillo ejemplo:

<img align="left" width="900"  float= "none" align="middle" src="figuras/NumpyPython2.png">



### Ejemplo 1

In [3]:
#timeit — Mide el tiempo de ejecución de pequeños fragmentos de código
test_list = list(range(1001))
%timeit sum(test_list)

4.78 μs ± 45.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
import numpy as np
test_array = np.arange(1001)
%timeit np.sum(test_array)

3.36 μs ± 86.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Ejemplo 2

<img align="left" width="900"  float= "none" align="middle" src="figuras/NumpyPython3.png">


In [5]:
n = 10000001

In [6]:
test_list  = list(range(n)) # Python
%timeit sum(test_list)

54.3 ms ± 2.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
test_array = np.arange(n)   # NumPy
%timeit np.sum(test_array)

4.8 ms ± 232 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### ¿Por qué esta diferencia? 
* Es más eficiente la manera en que se accede a los elementos de un array de **NumPy** con respecto a como *Python* procede a realizar tal tarea en sus estructuras de datos básicas.
* El número de comprobaciones intermedias a la hora de llevar a cabo cálculos numéricos es menor en  **NumPy**
* **Numpy** está escrito utilizando el lenguaje de programación C, que es bastante más rápido que *Python*


# Creando arreglos desde una lista

Se puede hacer uso de ``np.array`` para crear arreglos provenientes de una lista:

In [8]:
# Arreglo de enteros
a1= np.array([1, 4, 2, 5, 3])

In [9]:
a1.dtype

dtype('int64')

Recuerde que, a diferencia de las listas de Python, **NumPy está restringido a matrices que contienen el mismo tipo**. Si los tipos no coinciden, NumPy se ajustará si es posible (aquí, los enteros se cambian a flotante):

In [10]:
a2 = np.array([3.14, 4, 2, 3])

In [11]:
a2.dtype

dtype('float64')

In [12]:
print(a2)

[3.14 4.   2.   3.  ]


En el caso de tener un elemento string, todo el arreglo se cambiará a string 

In [13]:
a3 = np.array([1, 4, 'string', 5, 3.1])

In [14]:
a3.dtype

dtype('<U32')

In [15]:
#No es necesario el print para tener una salida
a3

array(['1', '4', 'string', '5', '3.1'], dtype='<U32')

Si queremos establecer explícitamente el tipo de datos del arreglo, podemos usar la opción ``dtype``:

In [16]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [17]:
np.array([1, 2, 3.1, 4.7], dtype='int')

array([1, 2, 3, 4])

Para crear una matriz de 2 filas y 3 columnas podríamos hacer lo siguiente

In [18]:
a4 = np.array([[1,2,3],[8,9,10]])
print(a4)

[[ 1  2  3]
 [ 8  9 10]]


A diferencia de las listas de Python, los arreglos de NumPy pueden ser explícitamente multidimensionales; aquí hay una forma de inicializar una matriz multidimensional utilizando una lista de listas:


In [19]:
# las listas anidadas dan como resultado matrices multidimensionales
import numpy as np
a5 = np.array([[2, 3, 4], [4, 5, 6], [6, 7, 8], [8, 9, 10]])
print(a5)

[[ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


In [20]:
# Para obtener la dimensión
a5.ndim

2

In [21]:
# Para obtener la forma (Filas, Columnas)
a5.shape

(4, 3)

In [22]:
a5.shape[0]

4

In [23]:
# Para obtener el número de elementos
a5.size

12

Para obtener algún  elemento **Arreglo[fila, columna]**


<font color='Green'> 
¿Cómo obtendría el **elemento 10** de a5 ?

[[ 2  3  4]<br>[ 4  5  6]<br>[ 6  7  8]<br> [ 8  9 **10**]]
</font> 

In [24]:
print(a5[3,2])

10


<font color='Green'> 
¿Cómo obtendría los elementos de la primera fila?
    
[**[ 2  3  4]**<br>[ 4  5  6]<br>[ 6  7  8]<br> [ 8  9 10]]

</font> 

In [25]:
# Método 1 
#  indice_inicio : indice_final (pero no esta incluido)
#     0  : 3 (el indice 3 no esta incluido)
#     0  : 3  --> [0,1,2] 
print(a5[0,:])

[2 3 4]


In [26]:
# Método 2 
# indice_inicio : indice_final
# Cuando no se coloca el inicio y final se tomarán todos los indices


<font color='Green'> 
¿Cómo obtendría los elementos de la ultima columna?

[[ 2  3  **4**]<br>[ 4  5  **6**]<br>[ 6  7  **8**]<br> [ 8  9 **10**]]

    
</font> 

In [27]:
# Método 1 
# Necesitamos las filas con índice 0,1,2,3
# Necesitamos los elementos de la columna con índice 2 o -1
# Utilizando indices numericos 

a5[:,-1]

array([ 4,  6,  8, 10])

In [28]:
# Método 2
# Necesitamos las filas con índice 0,1,2,3
# Necesitamos los elementos de la columna con índice 2 o -1
# Utilizando indices numericos 


In [29]:
# Método 3 
# Ya que se estan considerando todos los indices para las filas, se puede colocar solamente ":"


### Ejemplo de arreglo 3D

Matriz de ejemplo:
![Matriz 3D](figuras/3D_numpy.png )

In [30]:
a6 = np.array([[[1,2],[4,3],[7,4]] , [[2,3],[9,4],[7,5]] , [[1,0],[3,1],[0,2]] , [[9,6],[6,7],[9,8]] ])

In [31]:
print(a6)

[[[1 2]
  [4 3]
  [7 4]]

 [[2 3]
  [9 4]
  [7 5]]

 [[1 0]
  [3 1]
  [0 2]]

 [[9 6]
  [6 7]
  [9 8]]]


<div class="alert alert-success">
 1.   ¿Como obtendría la dimensión del arreglo?
</div> 

In [32]:
a6.ndim

3

<div class="alert alert-success">
    
2. ¿Cómo obtendría la fila **[ 1 2 ]** ?
    
</div> 

In [33]:
a6[0,0,:]

array([1, 2])

<div class="alert alert-success">
    
3. ¿Cómo obtendría el elemento **8**?
    
</div> 

In [34]:
a6[3,2,1]

np.int64(8)

In [35]:
a6[-1,-1,-1]

np.int64(8)

## Crear arreglos desde cero

Algunas veces es más eficiente crear arreglos desde cero utilizando rutinas integradas en NumPy.
Aquí hay varios ejemplos:

In [36]:
# Matriz entera de longitud 10 llena de ceros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
# Matriz de elementos flotantes 3x5 llena de unos
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
# Matriz de 3x5 con un número en particular 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [39]:
# Matriz llena de una secuencia lineal Comenzando en 0, terminando en 20, con un paso o delta de 2 
#(esto es similar a la función incorporada range ())
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [40]:
# Matriz de 50 valores espaciados uniformemente entre 0 y 1
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [41]:
# Matriz de cinco valores espaciados uniformemente entre 0 y 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [42]:
#  Haga una matriz de 3x3 de distribución uniforme valores aleatorios entre 0 y 1
np.random.random((3, 3))

array([[0.03251035, 0.89849237, 0.64029756],
       [0.03831433, 0.94892817, 0.89067661],
       [0.34000442, 0.18416815, 0.43271371]])

In [43]:
#  Matriz 3x3 de valores aleatorios normalmente distribuidos con media 0 y desviación estándar 1
np.random.normal(0, 1, (3, 3))

array([[ 0.18084881, -0.89948497,  0.34578126],
       [ 0.68610663, -0.97653148,  1.02661502],
       [ 0.32717902,  0.56755186, -0.15726879]])

In [44]:
# Matriz 3x3 de valores enteros aleatorios en el intervalo [0, 10) 
np.random.randint(0, 10, (3, 3))

array([[4, 2, 9],
       [8, 3, 9],
       [0, 7, 1]], dtype=int32)

In [45]:
# Crear una matriz identidad de 3x3 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Tipos de datos en NumPy 

**Los arreglos de NumPy contienen valores de un solo tipo**, por lo que es importante tener un conocimiento detallado de esos tipos y sus limitaciones. Debido a que NumPy está construido en C, los tipos serán familiares para los usuarios de C, Fortran y otros lenguajes relacionados.

Para construir un arreglo de un tipo en particular  se puede especificar utilizando un ``dtype`` y el tipo de dato:



In [46]:
a7 = np.zeros(10, dtype='int16')
a7

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [47]:
#utilizamos dtype para verificar el tipo de dato
a7.dtype

dtype('int16')

Los tipos de datos estándar de NumPy se enumeran en la siguiente tabla:


| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 